package spring.web.models;
// default package
// Generated Mar 1, 2023, 9:16:41 AM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CategoryId generated by hbm2java
 */
@Embeddable
public class CategoryId  implements java.io.Serializable {


     private int categoriesId;
     private int id;

    public CategoryId() {
    }

    public CategoryId(int categoriesId, int id) {
       this.categoriesId = categoriesId;
       this.id = id;
    }
   


    @Column(name="categories_id", nullable=false)
    public int getCategoriesId() {
        return this.categoriesId;
    }
    
    public void setCategoriesId(int categoriesId) {
        this.categoriesId = categoriesId;
    }


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoryId) ) return false;
		 CategoryId castOther = ( CategoryId ) other; 
         
		 return (this.getCategoriesId()==castOther.getCategoriesId())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCategoriesId();
         result = 37 * result + this.getId();
         return result;
   }   


}


