package spring.web.models;
// default package
// Generated Mar 1, 2023, 9:16:41 AM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ImagesId generated by hbm2java
 */
@Embeddable
public class ImagesId  implements java.io.Serializable {


     private int productCategoryCategoriesId;
     private int productCategoryId;
     private int productCategoryId1;
     private int productId;

    public ImagesId() {
    }

    public ImagesId(int productCategoryCategoriesId, int productCategoryId, int productCategoryId1, int productId) {
       this.productCategoryCategoriesId = productCategoryCategoriesId;
       this.productCategoryId = productCategoryId;
       this.productCategoryId1 = productCategoryId1;
       this.productId = productId;
    }
   


    @Column(name="product_category_categories_id", nullable=false)
    public int getProductCategoryCategoriesId() {
        return this.productCategoryCategoriesId;
    }
    
    public void setProductCategoryCategoriesId(int productCategoryCategoriesId) {
        this.productCategoryCategoriesId = productCategoryCategoriesId;
    }


    @Column(name="product_category_id", nullable=false)
    public int getProductCategoryId() {
        return this.productCategoryId;
    }
    
    public void setProductCategoryId(int productCategoryId) {
        this.productCategoryId = productCategoryId;
    }


    @Column(name="product_category_id1", nullable=false)
    public int getProductCategoryId1() {
        return this.productCategoryId1;
    }
    
    public void setProductCategoryId1(int productCategoryId1) {
        this.productCategoryId1 = productCategoryId1;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImagesId) ) return false;
		 ImagesId castOther = ( ImagesId ) other; 
         
		 return (this.getProductCategoryCategoriesId()==castOther.getProductCategoryCategoriesId())
 && (this.getProductCategoryId()==castOther.getProductCategoryId())
 && (this.getProductCategoryId1()==castOther.getProductCategoryId1())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductCategoryCategoriesId();
         result = 37 * result + this.getProductCategoryId();
         result = 37 * result + this.getProductCategoryId1();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


