package spring.web.models;
// default package
// Generated Mar 1, 2023, 9:16:41 AM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinColumns;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="flamingoo"
)
public class Product  implements java.io.Serializable {


     private ProductId id;
     private Category category;
     private String name;
     private String description;
     private int price;
     private int quantity;
     private Set<Color> colors = new HashSet<Color>(0);
     private Set<Images> imageses = new HashSet<Images>(0);
     private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);
     private Set<User> users = new HashSet<User>(0);

    public Product() {
    }

	
    public Product(ProductId id, Category category, String name, String description, int price, int quantity) {
        this.id = id;
        this.category = category;
        this.name = name;
        this.description = description;
        this.price = price;
        this.quantity = quantity;
    }
    public Product(ProductId id, Category category, String name, String description, int price, int quantity, Set<Color> colors, Set<Images> imageses, Set<OrderItems> orderItemses, Set<User> users) {
       this.id = id;
       this.category = category;
       this.name = name;
       this.description = description;
       this.price = price;
       this.quantity = quantity;
       this.colors = colors;
       this.imageses = imageses;
       this.orderItemses = orderItemses;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="categoryCategoriesId", column=@Column(name="category_categories_id", nullable=false) ), 
        @AttributeOverride(name="categoryId", column=@Column(name="category_id", nullable=false) ), 
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ) } )
    public ProductId getId() {
        return this.id;
    }
    
    public void setId(ProductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="category_id", referencedColumnName="categories_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="category_categories_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false) } )
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="product_colors", catalog="flamingoo", joinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_categories_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="color_id", nullable=false, updatable=false) })
    public Set<Color> getColors() {
        return this.colors;
    }
    
    public void setColors(Set<Color> colors) {
        this.colors = colors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Images> getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set<Images> imageses) {
        this.imageses = imageses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="order_items_products", catalog="flamingoo", joinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_categories_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="order_items_id", nullable=false, updatable=false), 
        @JoinColumn(name="order_items_order_details_id", nullable=false, updatable=false), 
        @JoinColumn(name="order_items_order_details_user_id", nullable=false, updatable=false) })
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_review_product", catalog="flamingoo", joinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_categories_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


