package spring.web.models;
// default package
// Generated Mar 1, 2023, 9:16:41 AM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ProductId generated by hbm2java
 */
@Embeddable
public class ProductId  implements java.io.Serializable {


     private int categoryCategoriesId;
     private int categoryId;
     private int id;

    public ProductId() {
    }

    public ProductId(int categoryCategoriesId, int categoryId, int id) {
       this.categoryCategoriesId = categoryCategoriesId;
       this.categoryId = categoryId;
       this.id = id;
    }
   


    @Column(name="category_categories_id", nullable=false)
    public int getCategoryCategoriesId() {
        return this.categoryCategoriesId;
    }
    
    public void setCategoryCategoriesId(int categoryCategoriesId) {
        this.categoryCategoriesId = categoryCategoriesId;
    }


    @Column(name="category_id", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductId) ) return false;
		 ProductId castOther = ( ProductId ) other; 
         
		 return (this.getCategoryCategoriesId()==castOther.getCategoryCategoriesId())
 && (this.getCategoryId()==castOther.getCategoryId())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCategoryCategoriesId();
         result = 37 * result + this.getCategoryId();
         result = 37 * result + this.getId();
         return result;
   }   


}


